platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'APP' do
    pod 'WoodPeckeriOS'
    pod 'FLEX'
#    pod 'DotzuX'
end

target 'iOSHook' do
    pod 'WoodPeckeriOS'
    pod 'FLEX'
#    pod 'DotzuX'
end